# Базовый образ с CUDA и cuDNN
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

# Установка зависимостей в один RUN для уменьшения слоев
RUN apt-get update && apt-get install -y \
    git \
    git-lfs \
    portaudio19-dev \
    python3-pyaudio \
    ffmpeg \
    python3-pip \
    curl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*  # Очистка кеша apt

    # Клонирование репозитория копирование модели Silero
RUN git clone https://github.com/Sanich137/ASR_FastAPI_WS_RU_sherpa-onnx && \
    curl -L https://github.com/snakers4/silero-vad/blob/v5.0/files/silero_vad.onnx?raw=true \
         -o /ASR_FastAPI_WS_RU_sherpa-onnx/models/VAD_silero_v5/silero_vad.onnx


    # установка остальных моделей
RUN cd ASR_FastAPI_WS_RU_sherpa-onnx && \
    git lfs install && \
    ls -la /ASR_FastAPI_WS_RU_sherpa-onnx/models/VAD_silero_v5/ && \
    cd models && \
    git clone https://huggingface.co/Alexanrd/GigaAMv2_CTC_RU_ASR_for_sherpa_onnx && \
    git clone https://huggingface.co/Alexanrd/sbert_punc_case_ru_onnx && \
    cd ..

WORKDIR /ASR_FastAPI_WS_RU_sherpa-onnx

# Установка Python-зависимостей
RUN pip install --no-cache-dir -r requirements.txt

# Открываем порт и запускаем приложение
EXPOSE 49153
CMD ["python3", "main.py"]